### PR TITLE
Improve Dockerization process

### PR DESCRIPTION
**Pull request by Maecenas**
#3 
Please consider using squash commit or interactive rebase `git rebase -i master` before merging.

### CODE REVIEW

**Comment by DarkKowalski** [comment]
Looks good,  once it's merged, Docker Hub will auto build new image and I will soon deploy it.

**Review by tsengkasing — APPROVED** [review]
LGTM

**Comment by Maecenas** [comment]
Things are getting complicated. Please let me have a try to rebase this branch.

**Comment by Maecenas** [comment]
Please consider `git reset --hard 9b057c5a0c && git push -f` on master branch. Or is it your wish to merge this PR into #3 and re-merge #3 into master? @tsengkasing

**Comment by tsengkasing** [comment]
Sorry for the trouble for My operations due to that I want to clean up some meaningless commit in the master branch.

**Comment by tsengkasing** [comment]
@DarkKowalski 
Shall I merge this PR ? Or you want to test it before ?
I know examination is annoying thus you can test it when you are free.

**Comment by DarkKowalski** [comment]
I have tested this docker image briefly and it works. So I think you can merge it.

**Comment by tsengkasing** [comment]
> I have tested this docker image briefly and it works. So I think you can merge it.

Thanks for your work.

**Pull request merged**
